### PR TITLE
Add configuration for team urls

### LINKED ISSUE #4: Make the team community URLs configurable
Add a configuration option for the team community URLs.  Don't make one option per team, since this would make a bigger mess of the configuration page.

jspayne did an experiment that seems to work as a good option: Use a string configuration option, and paste in JSON text (one line).  Then in the code, use json.loads() to interpret the info.

Note (for whatever default is included) that each URL should be a relative URL in the form: `/c/community@instance`.  This will ensure that the link will work regardless of which instance you are viewing it from.

### PR DESCRIPTION
**Pull request by jspayne**
Fixes #4

This is a little ugly because I didn't want to add 32 configuration boxes to the config page.  The configuration option accepts a python-style dict (*not* JSON, since this dict has a mix of integral & string keys).  I was able to copy & paste the table directly from the original in __init__ - you don't need to escape quotes or anything.

It will fall back to the internal table if the configuration key doesn't exist.

I used ast.lteral_eval because eval will execute code pasted into the config.

### CODE REVIEW

**Comment by benja810** [comment]
Why can't we use a JSON file? JSON supports number types? Even if we need to parse, I think it would be a better UX.

**Comment by jspayne** [comment]
JSON does not allow numbered *keys*, and the teamSubs dict has a mix of numbered and named keys.  I can see if I can hunt down where the "mlb" key is used.

I hadn't thought about using the configuration to specify a file, so I'll take a look at that possibility.  It already does that for custom mako templates, so there is precedent.

**Comment by jspayne** [comment]
@benja810 This should work better.  I ended up dropping the 'mlb' key because I searched the code and can't find a reference to it anywhere.

**Comment by jspayne** [comment]
This has been superseded by the json solution.

**Pull request closed without merging**
